version: '3.7'

services:

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_DB: example_database
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
